"""
app/routes/job_works.py
------------------------
Job Work generation: the document that hands a proforma invoice's goods on to
be worked on, normally as a size CONVERSION. Mirrors app/routes/
purchase_orders.py layer for layer, with the differences that follow from
what job work is - two parties on the one sheet (the FROM SELLER whose goods
are going out and the JOB MANUFACTURER doing the work, both Suppliers), and
DESIGN lines instead of product lines, entirely under the Job Manufacturer
card:

  * "To Product" (picked first) - the WHOLE catalog, not just the invoice's
    own products; its own designs are what the Design picker offers, fetched
    via /job-works/api/products/<id>/designs;
  * "Product" (picked second) - the invoice's own products, kept only to look
    up each chosen design's source_quantity off the invoice's packing list
    (matched by design NAME, since the design lives under a different
    catalog product on either side of the conversion);
  * per design line: Jobed Qty (source_quantity, fetched, read-only),
    Conversion Value and Extra Qty % (typed), then Converted Qty and Extra
    Qty and finally Job Quantity are all computed - see JobWorkItem's own
    docstring for the exact chain. Nothing is typed as "the" quantity; it is
    entirely derived.

A job work is normally started from an existing Proforma Invoice via
`?proforma_invoice_id=` (copying its details and its consignee in as a
one-time prefill), and the button that does so lives on that invoice's own
preview toolbar. The JW number is auto-generated as JW{YYYYMMDD}{seq-of-that-
day} and is never user-editable.
"""

from datetime import date

from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, g, abort, jsonify

from app.exceptions import ValidationError, PermissionDeniedError, NotFoundError
from app.utils import login_required, admin_required, verify_delete_password

job_works_bp = Blueprint("job_works", __name__, url_prefix="/job-works")

_HEADER_FIELDS = [
    "job_work_date", "proforma_invoice_id",
    "seller_supplier_id", "seller_name", "seller_address", "seller_pan", "seller_gstin",
    "manufacturer_supplier_id", "manufacturer_name", "manufacturer_address",
    "manufacturer_pan", "manufacturer_gstin",
    "seller_ref_no", "delivery_time", "advance_percent", "payment_terms", "remarks",
    "purchase_type", "tax_as_actual",
    "currency_code",
]


def _extract_header(form) -> dict:
    return {key: form.get(key, "") for key in _HEADER_FIELDS}


def _extract_items(form) -> list:
    """One row per design added to the job work. Every column posts as a
    parallel array the same way the purchase order form's product lines do -
    the rows are generated by the form's own script, so the arrays are always
    written together and stay in step. Conversion Value and Extra Qty % are
    the only figures actually typed; everything else the service computes or
    fetches itself (see JobWorkService._build_items)."""
    to_product_ids = form.getlist("item_to_product_id[]")
    to_product_names = form.getlist("item_to_product_name[]")
    product_ids = form.getlist("item_product_id[]")
    product_names = form.getlist("item_product_name[]")
    design_ids = form.getlist("item_design_id[]")
    design_names = form.getlist("item_design_name[]")
    conversion_values = form.getlist("item_conversion_value[]")
    extra_percents = form.getlist("item_extra_percent[]")

    def at(values_list, i, default=""):
        return values_list[i] if i < len(values_list) else default

    return [
        {
            "to_product_id": at(to_product_ids, i),
            "to_product_name": to_product_names[i],
            "product_id": at(product_ids, i),
            "product_name": at(product_names, i),
            "design_id": at(design_ids, i),
            "design_name": at(design_names, i),
            "conversion_value": at(conversion_values, i),
            "extra_percent": at(extra_percents, i),
        }
        for i in range(len(to_product_names))
    ]


def _extract_products(form) -> list:
    """One row per line of the Products card - a plain copy of
    purchase_orders._extract_items, posted the same way (parallel
    item_*[] arrays)."""
    product_ids = form.getlist("pl_product_id[]")
    product_names = form.getlist("pl_product_name[]")
    hsn_codes = form.getlist("pl_hsn_code[]")
    boxes = form.getlist("pl_quantity_boxes[]")
    values = form.getlist("pl_quantity_value[]")
    units = form.getlist("pl_unit[]")
    prices = form.getlist("pl_price_inr[]")
    price_pers = form.getlist("pl_price_per[]")
    products = []
    for i in range(len(product_names)):
        products.append({
            "product_id": product_ids[i] if i < len(product_ids) else "",
            "product_name": product_names[i],
            "hsn_code": hsn_codes[i] if i < len(hsn_codes) else "",
            "quantity_boxes": boxes[i] if i < len(boxes) else "",
            "quantity_value": values[i] if i < len(values) else "",
            "unit": units[i] if i < len(units) else "SQM",
            "price_inr": prices[i] if i < len(prices) else "",
            "price_per": price_pers[i] if i < len(price_pers) else "BOX",
        })
    return products


def _product_meta_map(products) -> dict:
    """product_id -> {'alt_qty', 'igst'} for the Products card's live
    preview - same helper purchase_orders._product_meta_map provides."""
    container = current_app.container
    result = {}
    for product in products:
        raw_id = product.get("product_id") if isinstance(product, dict) else product.product_id
        if not raw_id:
            continue
        try:
            product_id = int(raw_id)
        except (TypeError, ValueError):
            continue
        if product_id in result:
            continue
        try:
            catalog_product = container.product_service.get_product(product_id, g.user.company_id)
            result[product_id] = {
                "alt_qty": catalog_product.alternate_quantity or "", "igst": catalog_product.igst_percent or "",
                "unit": catalog_product.alternate_quantity_unit or "",
            }
        except NotFoundError:
            pass
    return result


def _form_context():
    """(proforma invoices, suppliers, products) for the form's pickers: the
    Start-from picker, the two party cards (both picked from the same
    Suppliers list), and the Job Manufacturer card's "To Product" dropdown -
    the WHOLE catalog, since job work converts a design into a different
    size and the target product is rarely on the invoice at all."""
    container = current_app.container
    invoices = container.proforma_invoice_service.list_all(g.user.company_id)
    suppliers = container.supplier_service.list_all(g.user.company_id)
    products = container.product_service.list_products(g.user.company_id)
    return invoices, suppliers, products


def _invoice_context(proforma_invoice_id) -> tuple:
    """(invoice products, exact quantities, design-only fallback quantities)
    for the form's "Product" dropdown and its source_quantity lookups - see
    JobWorkService.invoice_products / invoice_quantities. Empty when no
    invoice is chosen (or it isn't ours), which the form shows as "pick a
    proforma invoice first"."""
    if not proforma_invoice_id:
        return [], {}, {}
    container = current_app.container
    try:
        invoice = container.proforma_invoice_service.get(int(proforma_invoice_id), g.user.company_id)
    except (NotFoundError, ValueError, TypeError):
        return [], {}, {}
    products = container.job_work_service.invoice_products(invoice)
    by_product_and_design, by_design_only = container.job_work_service.invoice_quantities(
        g.user.company_id, invoice
    )
    # Dict keys can't be tuples in JSON - flattened to a "product_key||design"
    # string the form's own script splits back apart.
    quantities = {f"{key[0]}||{key[1]}": entry for key, entry in by_product_and_design.items()}
    return products, quantities, by_design_only


def _render_form(job_work, form_data, form_items, status=200, form_products=None):
    invoices, suppliers, products = _form_context()
    source_invoice_id = (form_data or {}).get("proforma_invoice_id") if form_data else (
        job_work.proforma_invoice_id if job_work else None
    )
    invoice_products, invoice_quantities, invoice_quantities_by_design = _invoice_context(source_invoice_id)
    pl_rows = form_products if form_products is not None else (job_work.products if job_work else [])
    return render_template(
        "job_works/form.html", job_work=job_work, invoices=invoices, suppliers=suppliers,
        products=products, form_data=form_data, form_items=form_items,
        invoice_products=invoice_products, invoice_quantities=invoice_quantities,
        invoice_quantities_by_design=invoice_quantities_by_design,
        invoice_product_meta_map=_product_meta_map(invoice_products),
        form_products=pl_rows, product_meta_map=_product_meta_map(pl_rows),
        today=date.today().isoformat(),
    ), status


@job_works_bp.route("/api/products/<int:product_id>/designs")
@login_required
def api_product_designs(product_id):
    """Flat {id, name} design list for one catalog product - the "To
    Product" dropdown's live design picker. Deliberately not the folder-
    browsing endpoint products.api_browse_designs uses elsewhere: a job work
    just needs the flat list, the same shape ProductService.
    list_designs_for_product already returns."""
    try:
        designs = current_app.container.product_service.list_designs_for_product(product_id, g.user.company_id)
    except NotFoundError:
        return jsonify({"error": "not found"}), 404
    return jsonify({"designs": [{"id": d.id, "name": d.design_name} for d in designs]})


@job_works_bp.route("/")
@login_required
def list_job_works():
    job_works = current_app.container.job_work_service.list_all(g.user.company_id)
    return render_template("job_works/list.html", job_works=job_works)


@job_works_bp.route("/new", methods=["GET", "POST"])
@login_required
def new_job_work():
    container = current_app.container
    if request.method == "POST":
        try:
            job_work = container.job_work_service.create(
                current_user=g.user, fields=_extract_header(request.form), raw_items=_extract_items(request.form),
                raw_products=_extract_products(request.form),
            )
            flash(f"Job work {job_work.job_work_number} created.", "success")
            return redirect(url_for("job_works.view_job_work", job_work_id=job_work.id))
        except (ValidationError, PermissionDeniedError) as e:
            flash(str(e), "error")
            return _render_form(None, request.form, _extract_items(request.form), status=400,
                                 form_products=_extract_products(request.form))

    prefill = None
    proforma_invoice_id = request.args.get("proforma_invoice_id")
    if proforma_invoice_id:
        try:
            invoice = container.proforma_invoice_service.get(int(proforma_invoice_id), g.user.company_id)
            prefill = container.job_work_service.build_prefill_from_proforma(invoice)
            prefill["job_work_date"] = date.today().isoformat()
        except (NotFoundError, ValueError):
            pass
    return _render_form(None, prefill, None)[0]


@job_works_bp.route("/<int:job_work_id>")
@login_required
def view_job_work(job_work_id):
    container = current_app.container
    try:
        job_work = container.job_work_service.get(job_work_id, g.user.company_id)
    except NotFoundError:
        abort(404)
    company = container.company_service.get(g.user.company_id)
    invoice = None
    if job_work.proforma_invoice_id:
        try:
            invoice = container.proforma_invoice_service.get(job_work.proforma_invoice_id, g.user.company_id)
        except NotFoundError:
            pass
    packing_lists = container.packing_list_service.list_for_job_work(job_work_id, g.user.company_id)
    return render_template("job_works/print.html", job_work=job_work, company=company,
                           proforma_invoice=invoice, packing_lists=packing_lists)


@job_works_bp.route("/<int:job_work_id>/edit", methods=["GET", "POST"])
@login_required
def edit_job_work(job_work_id):
    container = current_app.container
    try:
        job_work = container.job_work_service.get(job_work_id, g.user.company_id)
    except NotFoundError:
        abort(404)

    if request.method == "POST":
        try:
            container.job_work_service.update(
                current_user=g.user, job_work_id=job_work_id,
                fields=_extract_header(request.form), raw_items=_extract_items(request.form),
                raw_products=_extract_products(request.form),
            )
            flash(f"Job work {job_work.job_work_number} updated.", "success")
            return redirect(url_for("job_works.view_job_work", job_work_id=job_work_id))
        except (ValidationError, PermissionDeniedError) as e:
            flash(str(e), "error")
            return _render_form(job_work, request.form, _extract_items(request.form), status=400,
                                 form_products=_extract_products(request.form))

    return _render_form(job_work, None, None)[0]


@job_works_bp.route("/<int:job_work_id>/delete", methods=["POST"])
@login_required
def delete_job_work(job_work_id):
    if not verify_delete_password(g.user, request.form):
        flash("Incorrect password. Job work not deleted.", "error")
        return redirect(url_for("job_works.view_job_work", job_work_id=job_work_id))
    try:
        job_work = current_app.container.job_work_service.get(job_work_id, g.user.company_id)
        current_app.container.job_work_service.delete(g.user, job_work_id)
        flash(f"Job work {job_work.job_work_number} deleted.", "success")
    except (ValidationError, PermissionDeniedError) as e:
        flash(str(e), "error")
        return redirect(url_for("job_works.view_job_work", job_work_id=job_work_id))
    except NotFoundError:
        abort(404)
    return redirect(url_for("job_works.list_job_works"))


@job_works_bp.route("/<int:job_work_id>/versions")
@admin_required
def job_work_versions(job_work_id):
    container = current_app.container
    try:
        job_work = container.job_work_service.get(job_work_id, g.user.company_id)
    except NotFoundError:
        abort(404)
    versions = container.document_version_service.list_for_document("job_work", job_work_id)
    rows = [
        {
            "version_number": v.version_number,
            "created_at": v.created_at,
            "changed_by_name": v.changed_by_name,
            "url": url_for("job_works.view_job_work", job_work_id=job_work_id) if i == 0 else
                   url_for("job_works.view_job_work_version",
                           job_work_id=job_work_id, version_number=v.version_number),
        }
        for i, v in enumerate(versions)
    ]
    return render_template(
        "document_versions/list.html", document_number=job_work.job_work_number, versions=rows,
        back_url=url_for("job_works.view_job_work", job_work_id=job_work_id),
    )


@job_works_bp.route("/<int:job_work_id>/versions/<int:version_number>")
@admin_required
def view_job_work_version(job_work_id, version_number):
    container = current_app.container
    try:
        container.job_work_service.get(job_work_id, g.user.company_id)  # tenant-scope check
        historical_job_work, version = container.document_version_service.get_version(
            "job_work", job_work_id, version_number
        )
    except NotFoundError:
        abort(404)
    company = container.company_service.get(g.user.company_id)
    return render_template(
        "job_works/print.html", job_work=historical_job_work, company=company,
        proforma_invoice=None, historical_version=version,
    )
