"""
app/routes/job_ins.py
----------------------
Job In generation: the "JOBWORK INWARD CHALLAN / RETURN" sheet that receives
jobbed goods back from a job manufacturer. Mirrors app/routes/job_outs.py,
and is always raised against ONE job out - normally straight from that
challan's own preview toolbar via `?job_out_id=`.

Unlike a job out, a job in DOES carry line items: what actually came back is
typed at the door and this document is the only record of it. Those lines are
prefilled with the jobbed product and one row per design at the quantity
EXPECTED back (off the job out's own output designs), for the receiver to
correct to what actually arrived, with an "add design" picker offering every
other design of that product.

Typed here: STOCK INWARD NO / DATE, the job manufacturer's own return challan
(JW DELIVERY CHALLAN NO / DATE - their paperwork, not ours), the transport
block, and the received quantities. Read live off the job out: our own
receiver block, the Job Manufacturer (Sender), our own DELIVERY CHALLAN
NO/DATE and the PURCHASE INVOICE reference.

Saving a job in is what ADDS the jobbed product's designs to stock, completing
the cycle a job out starts by deducting the master's - see
JobInRepository.received_back_totals_by_design and InventoryService.
"""

from datetime import date

from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, g, abort

from app.exceptions import ValidationError, PermissionDeniedError, NotFoundError
from app.utils import login_required, admin_required, verify_delete_password

job_ins_bp = Blueprint("job_ins", __name__, url_prefix="/job-ins")

_HEADER_FIELDS = [
    "job_out_id", "stock_inward_no", "stock_inward_date",
    "jw_delivery_challan_no", "jw_delivery_challan_date",
    "transporter_name", "transport_gstin", "lr_no", "vehicle_no", "remarks",
]


def _extract_header(form) -> dict:
    return {key: form.get(key, "") for key in _HEADER_FIELDS}


def _extract_items(form) -> list:
    """One row per design received back. Every column posts as a parallel
    array, the same way the job work form's design lines do - the rows are
    generated by the form's own script, so the arrays stay in step."""
    product_ids = form.getlist("item_product_id[]")
    product_names = form.getlist("item_product_name[]")
    hsn_codes = form.getlist("item_hsn_code[]")
    design_ids = form.getlist("item_design_id[]")
    design_names = form.getlist("item_design_name[]")
    boxes = form.getlist("item_quantity_boxes[]")

    def at(values, i, default=""):
        return values[i] if i < len(values) else default

    return [
        {
            "product_id": at(product_ids, i),
            "product_name": product_names[i],
            "hsn_code": at(hsn_codes, i),
            "design_id": at(design_ids, i),
            "design_name": at(design_names, i),
            "quantity_boxes": at(boxes, i),
        }
        for i in range(len(product_names))
    ]


def _render_form(job_in, form_data, form_items, status=200):
    """The form needs the job out this is received against (for its jobbed
    products and their design lists) plus the transporter directory for the
    transport pickers."""
    container = current_app.container
    job_outs = container.job_out_service.list_all(g.user.company_id)
    transporters = container.transporter_service.list_all(g.user.company_id)

    source_job_out_id = (form_data or {}).get("job_out_id") if form_data else (
        job_in.job_out_id if job_in else None
    )
    jobbed_products = []
    if source_job_out_id:
        try:
            job_out = container.job_out_service.get(int(source_job_out_id), g.user.company_id)
            jobbed_products = container.job_in_service.jobbed_products_for_job_out(
                job_out, g.user.company_id
            )
        except (NotFoundError, ValidationError, ValueError, TypeError):
            jobbed_products = []

    rows = form_items if form_items is not None else (job_in.items if job_in else
                                                      (form_data or {}).get("items") or [])
    return render_template(
        "job_ins/form.html", job_in=job_in, job_outs=job_outs, transporters=transporters,
        jobbed_products=jobbed_products, form_data=form_data, form_items=rows,
        today=date.today().isoformat(),
    ), status


@job_ins_bp.route("/")
@login_required
def list_job_ins():
    job_ins = current_app.container.job_in_service.list_all(g.user.company_id)
    return render_template("job_ins/list.html", job_ins=job_ins)


@job_ins_bp.route("/new", methods=["GET", "POST"])
@login_required
def new_job_in():
    container = current_app.container
    if request.method == "POST":
        try:
            job_in = container.job_in_service.create(
                current_user=g.user, fields=_extract_header(request.form),
                raw_items=_extract_items(request.form),
            )
            flash(f"Job in {job_in.stock_inward_no} created.", "success")
            return redirect(url_for("job_ins.view_job_in", job_in_id=job_in.id))
        except (ValidationError, PermissionDeniedError) as e:
            flash(str(e), "error")
            return _render_form(None, request.form, _extract_items(request.form), status=400)

    prefill = None
    job_out_id = request.args.get("job_out_id")
    if job_out_id:
        try:
            job_out = container.job_out_service.get(int(job_out_id), g.user.company_id)
            prefill = container.job_in_service.build_prefill_from_job_out(job_out, g.user.company_id)
        except (NotFoundError, ValidationError, ValueError):
            pass
    return _render_form(None, prefill, (prefill or {}).get("items"))[0]


@job_ins_bp.route("/<int:job_in_id>")
@login_required
def view_job_in(job_in_id):
    """The job in's detail page IS its printed sheet, same as a job out."""
    container = current_app.container
    try:
        job_in = container.job_in_service.get(job_in_id, g.user.company_id)
        sheet = container.job_in_service.build_sheet(job_in, g.user.company_id)
    except (NotFoundError, ValidationError):
        abort(404)
    return render_template("job_ins/print.html", job_in=job_in, **sheet)


@job_ins_bp.route("/<int:job_in_id>/edit", methods=["GET", "POST"])
@login_required
def edit_job_in(job_in_id):
    container = current_app.container
    try:
        job_in = container.job_in_service.get(job_in_id, g.user.company_id)
    except NotFoundError:
        abort(404)

    if request.method == "POST":
        try:
            container.job_in_service.update(
                current_user=g.user, job_in_id=job_in_id, fields=_extract_header(request.form),
                raw_items=_extract_items(request.form),
            )
            flash(f"Job in {job_in.stock_inward_no} updated.", "success")
            return redirect(url_for("job_ins.view_job_in", job_in_id=job_in_id))
        except (ValidationError, PermissionDeniedError) as e:
            flash(str(e), "error")
            return _render_form(job_in, request.form, _extract_items(request.form), status=400)

    return _render_form(job_in, None, None)[0]


@job_ins_bp.route("/<int:job_in_id>/delete", methods=["POST"])
@login_required
def delete_job_in(job_in_id):
    if not verify_delete_password(g.user, request.form):
        flash("Incorrect password. Job in not deleted.", "error")
        return redirect(url_for("job_ins.view_job_in", job_in_id=job_in_id))
    try:
        job_in = current_app.container.job_in_service.get(job_in_id, g.user.company_id)
        current_app.container.job_in_service.delete(g.user, job_in_id)
        flash(f"Job in {job_in.stock_inward_no} deleted. Its stock has been removed.", "success")
    except (ValidationError, PermissionDeniedError) as e:
        flash(str(e), "error")
        return redirect(url_for("job_ins.view_job_in", job_in_id=job_in_id))
    except NotFoundError:
        abort(404)
    return redirect(url_for("job_ins.list_job_ins"))


@job_ins_bp.route("/<int:job_in_id>/versions")
@admin_required
def job_in_versions(job_in_id):
    container = current_app.container
    try:
        job_in = container.job_in_service.get(job_in_id, g.user.company_id)
    except NotFoundError:
        abort(404)
    versions = container.document_version_service.list_for_document("job_in", job_in_id)
    rows = [
        {
            "version_number": v.version_number,
            "created_at": v.created_at,
            "changed_by_name": v.changed_by_name,
            "url": url_for("job_ins.view_job_in", job_in_id=job_in_id) if i == 0 else
                   url_for("job_ins.view_job_in_version",
                           job_in_id=job_in_id, version_number=v.version_number),
        }
        for i, v in enumerate(versions)
    ]
    return render_template(
        "document_versions/list.html", document_number=job_in.stock_inward_no, versions=rows,
        back_url=url_for("job_ins.view_job_in", job_in_id=job_in_id),
    )


@job_ins_bp.route("/<int:job_in_id>/versions/<int:version_number>")
@admin_required
def view_job_in_version(job_in_id, version_number):
    container = current_app.container
    try:
        container.job_in_service.get(job_in_id, g.user.company_id)  # tenant-scope check
        historical_job_in, version = container.document_version_service.get_version(
            "job_in", job_in_id, version_number
        )
        sheet = container.job_in_service.build_sheet(historical_job_in, g.user.company_id)
    except (NotFoundError, ValidationError):
        abort(404)
    return render_template(
        "job_ins/print.html", job_in=historical_job_in, historical_version=version, **sheet
    )
